/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: deadricpaldin (https://sketchfab.com/deadricpaldin)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/white-letter-m-a53489ca4ba24096abbc7fde916ba780
title: White Letter M
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'



export function Model(props) {
  
  
  const { nodes, materials } = useGLTF('/m.gltf')
  
  
  return (
    <group {...props} dispose={null} >
      <group scale={0.03} rotation={[0.01, 0, 0]} >
        <mesh  geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']}/>
        
      </group>
    </group>
  )
}

useGLTF.preload('/m.gltf')

export default Model;

